### ISSUE TITLE
Example via nestjs - not working

### ISSUE THREAD

**Issue by felixunivers** [marianozunino/openssl-ts#5]
I ported openssl-ts to a sample nodejs/nestjs app
NodeJs ver:  18.6.0
NestJs ver: 9.1.1

	import { Injectable } from '@nestjs/common';
	import { openssl } from 'openssl-ts';

	@Injectable()
	export class OpenSslService {

	  async generateKey() {
		const output = await openssl(['genrsa', '-out', 'private.key', '2048']);
		console.log(output.toString());
	  }

	}

I get an error on the line:

    const output = await openssl(['genrsa', '-out', 'private.key', '2048']);

Here is the error:

	Error: spawn openssl ENOENT
		at Process.onexit (node:internal/child_process:283:19)
		at onErrorNT (node:internal/child_process:476:16)
		at processTicksAndRejections (node:internal/process/task_queues:82:21) {
	  errno: -4058,
	  code: 'ENOENT',
	  syscall: 'spawn openssl',
	  path: 'openssl',
	  spawnargs: [ 'genrsa', '-out', 'private.key', '2048' ]
	}

**Comment by marianozunino** [comment]
Hey! @felixunivers do you actually have openssl on your `PATH`?

This package does not provide the openssl binary, it is just a wrapper for it. 
Execute: `which openssl` to find out if you actually have it.

**Comment by marianozunino** [comment]
Added a NestJs example: https://github.com/marianozunino/openssl-ts/tree/master/example/nestjs-example
Updated the Readme to remark that this pkg is a **wrapper**
