### ISSUE TITLE
Provide examples for stdin with -in parameter

### ISSUE THREAD

**Issue by stweiz** [marianozunino/openssl-ts#8]
I'm trying to generate a new certificate with a csr. For this I have to pass the file path to the csr to the `-in` parameter.
I don't want to set a file and instead provide the csr content via stdin.

This works from the CLI with:

```bash
cat client.csr.pem | openssl ca -config openssl_intermediate_ca.conf -extensions usr_cert -days 365 -notext -md sha256 -in /dev/stdin --batch
```

In Node.js I can't use `/dev/stdin` as this is an input from the method. So how can I provide stdin to the `-in` parameter from OpenSSL?

My current try looks like this:

```node.js
const buffer = await openssl(
      [
        'ca',
        '-config',
        'openssl_intermediate_ca.conf',
        '-extensions',
        'usr_cert',
        '-days',
        '3650',
        '-notext',
        '-md',
        'sha256',
        '--batch',
        '-in',
      ],
      { openSSLPath, stdin: csrBuffer },
    );
```

**Comment by marianozunino** [comment]
Could you provide all the commands in order so I can replicate the same scenario?
- generating a client.csr.pem
- openssl_intermediate_ca.conf contents 
- and so on...
--- 

FWIW

This:
```bash
cat test/__resources__/signed.mobileprovision | openssl smime -verify -inform DER -noverify -in /dev/stdin
```
is the same as this:
```bash
cat test/__resources__/signed.mobileprovision | openssl- smime -verify -inform DER -noverify
```

So, given your example it would be the same as:

```ts
const buffer = await openssl(
      [
        'ca',
        '-config',
        'openssl_intermediate_ca.conf',
        '-extensions',
        'usr_cert',
        '-days',
        '3650',
        '-notext',
        '-md',
        'sha256',
        '--batch',
      ],
      { openSSLPath, stdin: csrBuffer },
    );
```

But once again, can't reproduce the example without all the info. Not an openssl expert.
